{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "."
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-8d108ce001db>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mwhile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\".\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mend\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m''\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m     \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m100\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import time\n",
    "\n",
    "while(True):\n",
    "    print(\".\",end='')\n",
    "    time.sleep(100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "S:0 S:1 S:2 S:3 S:4 S:5 S:6 S:7 S:8 S:9 S:10 S:11 S:12 S:13 S:14 S:15 S:16 S:17 S:18 S:19 S:20 S:21 S:22 S:23 S:24 S:25 S:26 S:27 S:28 S:29 S:30 S:31 S:32 S:33 S:34 S:35 S:36 S:37 S:38 S:39 S:40 S:41 S:42 S:43 S:44 S:45 S:46 S:47 S:48 S:49 S:50 S:51 S:52 S:53 S:54 S:55 S:56 S:57 S:58 S:59 S:60 S:61 S:62 S:63 S:64 S:65 S:66 S:67 S:68 S:69 S:70 S:71 S:72 S:73 S:74 S:75 S:76 S:77 S:78 S:79 S:80 S:81 S:82 S:83 S:84 S:85 S:86 S:87 S:88 S:89 S:90 S:91 S:92 S:93 S:94 S:95 S:96 S:97 S:98 S:99 S:100 S:101 S:102 S:103 S:104 S:105 S:106 S:107 S:108 S:109 S:110 S:111 S:112 S:113 S:114 S:115 S:116 S:117 S:118 S:119 S:120 S:121 S:122 S:123 S:124 S:125 S:126 S:127 S:128 S:129 S:130 S:131 S:132 S:133 S:134 S:135 S:136 S:137 S:138 S:139 S:140 S:141 S:142 S:143 S:144 S:145 S:146 S:147 S:148 S:149 S:150 S:151 S:152 S:153 S:154 S:155 S:156 S:157 S:158 S:159 S:160 S:161 S:162 S:163 S:164 S:165 S:166 S:167 S:168 S:169 S:170 S:171 S:172 S:173 S:174 S:175 S:176 S:177 S:178 S:179 S:180 S:181 S:182 S:183 S:184 S:185 S:186 S:187 S:188 S:189 S:190 S:191 S:192 S:193 S:194 S:195 S:196 S:197 S:198 S:199 S:200 S:201 S:202 S:203 S:204 S:205 S:206 S:207 S:208 S:209 S:210 S:211 S:212 S:213 S:214 S:215 S:216 S:217 S:218 S:219 S:220 S:221 S:222 S:223 S:224 S:225 S:226 S:227 S:228 S:229 S:230 S:231 S:232 S:233 S:234 S:235 S:236 S:237 S:238 S:239 S:240 S:241 S:242 S:243 S:244 S:245 S:246 S:247 S:248 S:249 S:250 S:251 S:252 S:253 S:254 S:255 S:256 S:257 S:258 S:259 S:260 S:261 S:262 S:263 S:264 S:265 S:266 S:267 S:268 S:269 S:270 S:271 S:272 S:273 S:274 S:275 S:276 S:277 S:278 S:279 S:280 S:281 S:282 S:283 S:284 S:285 S:286 S:287 S:288 S:289 S:290 S:291 S:292 S:293 S:294 S:295 S:296 S:297 S:298 S:299 S:300 S:301 S:302 S:303 S:304 S:305 S:306 S:307 S:308 S:309 S:310 S:311 S:312 S:313 S:314 S:315 S:316 S:317 S:318 S:319 S:320 S:321 S:322 S:323 S:324 S:325 S:326 S:327 S:328 S:329 S:330 S:331 S:332 S:333 S:334 S:335 S:336 S:337 S:338 S:339 S:340 S:341 S:342 S:343 S:344 S:345 S:346 S:347 S:348 S:349 S:350 S:351 S:352 S:353 S:354 S:355 S:356 S:357 S:358 S:359 S:360 S:361 S:362 S:363 S:364 S:365 S:366 S:367 S:368 S:369 S:370 S:371 S:372 S:373 S:374 S:375 S:376 S:377 S:378 S:379 S:380 S:381 S:382 S:383 S:384 S:385 S:386 S:387 S:388 S:389 S:390 S:391 S:392 S:393 S:394 S:395 S:396 S:397 S:398 S:399 S:400 S:401 S:402 S:403 S:404 S:405 S:406 S:407 S:408 S:409 S:410 S:411 S:412 S:413 S:414 S:415 S:416 S:417 S:418 S:419 S:420 S:421 S:422 S:423 S:424 S:425 S:426 S:427 S:428 S:429 S:430 S:431 S:432 S:433 S:434 S:435 S:436 S:437 S:438 S:439 S:440 S:441 S:442 S:443 S:444 S:445 S:446 S:447 S:448 S:449 S:450 S:451 S:452 S:453 S:454 S:455 S:456 S:457 S:458 S:459 S:460 S:461 S:462 S:463 S:464 S:465 S:466 S:467 S:468 S:469 S:470 S:471 S:472 S:473 S:474 S:475 S:476 S:477 S:478 S:479 S:480 S:481 S:482 S:483 ExceptionS:484 ExceptionS:485 ExceptionS:486 ExceptionS:487 ExceptionS:488 ExceptionS:489 ExceptionS:490 ExceptionS:491 ExceptionS:492 ExceptionS:493 ExceptionS:494 ExceptionS:495 ExceptionS:496 ExceptionS:497 ExceptionS:498 ExceptionS:499 Exception>>>>>>1.028425931930542\n",
      "E:0 E:1 E:5 E:2 E:4 E:3 E:6 E:13 E:11 E:7 E:12 E:8 E:10 E:9 E:14 E:17 E:15 E:16 E:18 E:24 E:22 E:19 E:23 E:20 E:25 E:21 E:26 E:27 E:28 E:29 E:30 E:31 E:32 E:33 E:34 E:35 E:36 E:37 E:38 E:39 E:40 E:41 E:42 E:43 E:44 E:45 E:46 E:47 E:48 E:49 E:50 E:51 E:52 E:53 E:54 E:55 E:56 E:57 E:58 E:59 E:60 E:61 E:62 E:63 E:64 E:65 E:66 E:67 E:68 E:69 E:70 E:71 E:72 E:73 E:74 E:75 E:76 E:77 E:78 E:79 E:80 E:81 E:82 E:83 E:84 E:85 E:86 E:87 E:88 E:89 E:90 E:91 E:92 E:93 E:94 E:95 E:96 E:97 E:98 E:99 E:100 E:101 E:102 E:103 E:104 E:106 E:105 E:107 E:108 E:109 E:110 E:111 E:112 E:113 E:114 E:115 E:116 E:117 E:118 E:119 E:120 E:121 E:122 E:123 E:124 E:125 E:126 E:127 E:128 E:129 E:130 E:131 E:132 E:133 E:134 E:135 E:136 E:137 E:138 E:139 E:140 E:141 E:142 E:143 E:144 E:145 E:146 E:147 E:148 E:149 E:150 E:151 E:152 E:153 E:154 E:155 E:156 E:157 E:158 E:159 E:160 E:161 E:162 E:163 E:164 E:165 E:166 E:167 E:169 E:168 E:170 E:171 E:172 E:173 E:174 E:175 E:176 E:177 E:178 E:179 E:180 E:181 E:182 E:183 E:184 E:185 E:186 E:187 E:188 E:189 E:190 E:191 E:192 E:193 E:194 E:195 E:196 E:197 E:198 E:199 E:200 E:201 E:202 E:203 E:204 E:205 E:206 E:207 E:208 E:209 E:210 E:211 E:212 E:213 E:214 E:215 E:216 E:217 E:218 E:219 E:220 E:221 E:222 E:223 E:224 E:225 E:226 E:227 E:228 E:229 E:230 E:231 E:232 E:233 E:234 E:235 E:236 E:237 E:238 E:239 E:240 E:241 E:242 E:243 E:244 E:245 E:246 E:247 E:248 E:249 E:250 E:251 E:252 E:253 E:254 E:255 E:256 E:257 E:258 E:259 E:260 E:261 E:262 E:263 E:264 E:265 E:266 E:267 E:268 E:269 E:270 E:271 E:272 E:273 E:274 E:275 E:276 E:277 E:278 E:279 E:280 E:281 E:282 E:283 E:284 E:285 E:286 E:287 E:288 E:289 E:290 E:291 E:292 E:293 E:294 E:295 E:296 E:297 E:298 E:299 E:300 E:301 E:302 E:303 E:304 E:305 E:306 E:307 E:308 E:309 E:310 E:311 E:312 E:313 E:314 E:315 E:319 E:318 E:316 E:321 E:317 E:320 E:322 E:323 E:324 E:325 E:326 E:327 E:328 E:329 E:330 E:331 E:332 E:333 E:334 E:335 E:336 E:337 E:338 E:340 E:341 E:342 E:343 E:339 E:344 E:345 E:346 E:347 E:348 E:349 E:350 E:351 E:352 E:353 E:354 E:355 E:356 E:357 E:358 E:359 E:360 E:361 E:362 E:363 E:365 E:364 E:366 E:367 E:368 E:369 E:370 E:371 E:372 E:373 E:374 E:375 E:376 E:377 E:378 E:380 E:379 E:381 E:382 E:383 E:384 E:385 E:386 E:387 E:388 E:389 E:390 E:391 E:392 E:393 E:394 E:395 E:396 E:397 E:398 E:399 E:400 E:401 E:402 E:403 E:404 E:405 E:406 E:407 E:408 E:409 E:410 E:411 E:412 E:413 E:414 E:415 E:416 E:417 E:418 E:419 E:420 E:421 E:422 E:423 E:424 E:425 E:426 E:427 E:428 E:429 E:430 E:431 E:432 E:433 E:435 E:434 E:436 E:437 E:438 E:439 E:440 E:441 E:442 E:443 E:444 E:445 E:446 E:447 E:448 E:449 E:450 E:451 E:452 E:453 E:454 E:455 E:456 E:457 E:458 E:459 E:460 E:461 E:462 E:463 E:464 E:465 E:466 E:467 E:468 E:469 E:470 E:471 E:472 E:473 E:474 E:475 E:476 E:477 E:478 E:479 E:480 E:481 E:482 =======================10.70689868927002\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-987:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-987, started 140139525560064)>>\n",
      "Exception in thread Thread-989:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-989, started 140139504580352)>>\n",
      "Exception in thread Thread-988:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-988, started 140139515070208)>>\n",
      "Exception in thread Thread-991:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-991, started 140139483600640)>>\n",
      "Exception in thread Thread-992:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-992, started 140139473110784)>>\n",
      "Exception in thread Thread-990:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-990, started 140139494090496)>>\n",
      "Exception in thread Thread-993:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-993, started 140139462620928)>>\n",
      "Exception in thread Thread-994:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-994, started 140139452131072)>>\n",
      "Exception in thread Thread-995:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-995, started 140139441641216)>>\n",
      "Exception in thread Thread-996:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-996, started 140139431151360)>>\n",
      "Exception in thread Thread-997:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-997, started 140139420661504)>>\n",
      "Exception in thread Thread-998:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-998, started 140139410171648)>>\n",
      "Exception in thread Thread-999:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-999, started 140139399681792)>>\n",
      "Exception in thread Thread-1000:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-1000, started 140139389191936)>>\n",
      "Exception in thread Thread-1003:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-1003, started 140139357722368)>>\n",
      "Exception in thread Thread-1001:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-1001, started 140139378702080)>>\n",
      "Exception in thread Thread-1002:\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 7, in worker\n",
      "    print ('S:%s ' % num, end=\"\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "  File \"/root/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "  File \"<ipython-input-2-af3c9a0df754>\", line 12, in worker\n",
      "    print (\"Exception\")\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 376, in write\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 203, in schedule\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 146, in socket\n",
      "  File \"/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 58, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 330, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-1002, started 140139368212224)>>\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import time\n",
    "\n",
    "def worker(num):\n",
    "    try:\n",
    "        \"\"\"thread worker function\"\"\"\n",
    "        print ('S:%s ' % num, end=\"\")\n",
    "        time.sleep(10)\n",
    "        print ('E:%s ' % num, end=\"\")\n",
    "        return\n",
    "    except Exception:\n",
    "        print (\"Exception\")\n",
    "    \n",
    "\n",
    "a = time.time()\n",
    "threads = []\n",
    "for i in range(500):\n",
    "    t = threading.Thread(target=worker, args=(i,))\n",
    "    threads.append(t)\n",
    "    t.start()\n",
    "    \n",
    "b = time.time()\n",
    "print (\">>>>>>\" + str(b-a))\n",
    "\n",
    "for t in threads:\n",
    "    t.join()\n",
    "    \n",
    "c = time.time()\n",
    "print (\"=======================\" + str(c-a))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
